import faker from "faker";
export const userRows = [
  {
    id: 1,
    username: faker.name.firstName(),
    avatar: faker.image.avatar(),
    email: faker.internet.email(),
    status: "active",
    transaction: faker.finance.amount(),
  },
  {
    id: 2,
    username: faker.name.firstName(),
    avatar: faker.image.avatar(),
    email: faker.internet.email(),
    status: "active",
    transaction: faker.finance.amount(),
  },
  {
    id: 3,
    username: faker.name.firstName(),
    avatar: faker.image.avatar(),
    email: faker.internet.email(),
    status: "active",
    transaction: faker.finance.amount(),
  },
  {
    id: 4,
    username: faker.name.firstName(),
    avatar: faker.image.avatar(),
    email: faker.internet.email(),
    status: "active",
    transaction: faker.finance.amount(),
  },
  {
    id: 5,
    username: faker.name.firstName(),
    avatar: faker.image.avatar(),
    email: faker.internet.email(),
    status: "active",
    transaction: faker.finance.amount(),
  },
  {
    id: 6,
    username: faker.name.firstName(),
    avatar: faker.image.avatar(),
    email: faker.internet.email(),
    status: "active",
    transaction: faker.finance.amount(),
  },
  {
    id: 7,
    username: faker.name.firstName(),
    avatar: faker.image.avatar(),
    email: faker.internet.email(),
    status: "active",
    transaction: faker.finance.amount(),
  },
  {
    id: 8,
    username: faker.name.firstName(),
    avatar: faker.image.avatar(),
    email: faker.internet.email(),
    status: "active",
    transaction: faker.finance.amount(),
  },
  {
    id: 9,
    username: faker.name.firstName(),
    avatar: faker.image.avatar(),
    email: faker.internet.email(),
    status: "active",
    transaction: faker.finance.amount(),
  },
  {
    id: 10,
    username: faker.name.firstName(),
    avatar: faker.image.avatar(),
    email: faker.internet.email(),
    status: "active",
    transaction: faker.finance.amount(),
  },
];
